name: cafeproject
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_native_splash:
  color: '#9c7c6c'
  image: 'assets/picture.png'
  android_12:
    image: 'assets/picture.png'

flutter:
  uses-material-design: true
  assets:
    - assets/anime.json


