name: cafeproject
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  lottie: ^3.1.2
  google_maps_flutter: ^2.9.0
  sqflite: ^2.3.3+1
  json_annotation: ^4.9.0
  intl: ^0.19.0
  get: ^4.3.8
  jwt_decoder: ^2.0.1
#  セキュリティー関連
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  hooks_riverpod: ^2.4.10
  flutter_secure_storage: ^9.2.2
  go_router: ^14.6.1
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  flutter_lints: ^3.0.0
# セキュリティー
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8
flutter_native_splash:
  color: '#FFFFFF'
  image: 'assets/picture.png'
  android_12:
    image: 'assets/picture.png'

flutter:
  uses-material-design: true
  assets:
    - assets/anime.json


